---
title: "Research"
description: | 
  I apply my data science and mathematical skills to interdisciplinary research problems in evolution of language, biology, and social behavior dynamics.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Recent Projects

### Examining and Modeling Police Response and Crime Reporting

*Collaborators:* Nanami Taono, Ben Yarrish, Laurel Ponce, and Sajid Bin Mahammud. ^[These collaborators where undergraduate students.]

This project investigates the relationship between crime rates and policing in the United States. We are using mathematical and statistical modeling, data science methods, and city-wide data to answer key questions, such as: How does law enforcement response vary with changes in crime rates? How do community perceptions of law enforcement change based on their presence? What are the effects of police presence on marginalized communities? The project's findings will inform public policy and enhance community-police relations.

**Posters:**

  - [A Data-Driven Model of Portland Policing](https://drive.google.com/file/d/1jWw1Fgi-mO2xMuo23TSDezO-82lAwoUV/view?usp=sharing){target="_blank"}
  - [Ridge Regression Model to Analyze Portland Police Dispatch Calls](https://drive.google.com/file/d/1OayCFTF0AQLoutCYAdtvRE9ASJQd0yR4/view?usp=sharing){target="_blank"}
  
### Statistical Modeling of Word Rank Evolution

*Collaborators:* [Rick Dale](https://co-mind.org/rick/){target="_blank"} & [Suzanne Sindi](https://www.sindilab.com/){target="_blank"}

The project goal is to model word rank evolution using a Wright-Fisher inspired
model. Google Ngram data is used to analyze eight languages and compared it to
the model that simulates drift evolution. The time-series evolutionary dynamics of
word ranks are investigated by adjusting the model parameters and comparing it to
the language data.

**Preprint:**

  - [A Statistical Model of Word Rank Evolution](https://arxiv.org/abs/2107.09948){target="_blank"}

## Past Projects

### Analysis of Twitter Texts

*Collaborators:* [Maia Powell](https://www.mmpowell.com/){target="_blank"}, Ayme Tomson, [Suzanne Sindi](https://www.sindilab.com/){target="_blank"}, & [Arnold Kim](https://faculty.ucmerced.edu/adkim/){target="_blank"}

The goal is to uncover the discourse and evolution behind certain hashtag social movements using NLP methods, machine learning algorithms, and language models. Twitter data was collected and processed using NLTK and several Python tools.

**Poster:**

  - [Evolving Contextual Semantics](https://drive.google.com/file/d/1Hh3E-tnvSJa-x8v_36IfPpsXMuXsZKMB/view){target="_blank"}

### Performance Analysis on Question Answering

*Collaborators:* Sam Nguyen & Juanita Ordonez

The objective was to fine-tune and evaluate three language models named BERT, ALBERT, and LongFormer on question answering data set called DuoRC where it contains movie plots with narrative structures. Due to the complexity and length of narrative texts, these models are needed to not only answer the question but must also go beyond its capabilities to perform complex reasoning and reading comprehension to infer answers to questions.

**Preprint:**

  - [Grid Search Hyperparameter Benchmarking of BERT, ALBERT, and LongFormer on DuoRC](https://arxiv.org/abs/2101.06326){target="_blank"}

**Presentation:**

  - [Word Embedding Models Performance Analysis on a Question Answering Task](https://drive.google.com/file/d/1emUr4XkeDUDWoROAFodLDpknpIohzs2L/view){target="_blank"}

### Machine Learning Application on Opacity

*Collaborators:* Robert C. Blake & Ben C. Yee

 The objective was to encode opacity - a material property on how much radiation can pass through it - into a neural network as a surrogate model against an existing atomic physics code.

**Poster:**

  - [Application of Convolutional Neural Network on Radiative Opacity Computations](https://drive.google.com/file/d/1FdpiriX5I6PTBupLxNbdwuLGCFnKeZTx/view){target="_blank"}

### Twitter Network Analysis of the California Camp Fire

*Collaborators:* [Maia Powell](https://www.mmpowell.com/){target="_blank"} & Matthew Mondares

The goal was to explore the spread of information generated by Twitter bots during the 2018 California Camp Fire disaster utilizing user-user and hashtag co-occurrence networks. Twitter bots are users who have automated repetitive and straightforward tweets. Most of them post, repost, or like other tweets to spread information faster than actual users for an unknown large-scale goal.

**Report:**

  - [Twitter Network Analysis of the California Camp Fire](https://stressosaurus.github.io/ggs-twitter-camp-fire/){target="_blank"}

### Predictive Modeling of Flood Susceptibility

*Collaborators:* Madeline Brown, Ritesh Sharma, & Umesh Krishnamurthy

This project was about modeling flood risk given multiple factors such as scale, demographics, risk perceptions, topology, soil moisture, and precipitation. The general goal was to develop a model for real-time predictions to alert and inform communities of flood risks.

**Presentation:** 
  
  - [Predictive Modeling of Flood Susceptibility: Phase 1](https://drive.google.com/file/d/18roBmru1hyqDkK3co6HKpTBuaLf1WbBU/view?usp=sharing){target="_blank"}

### Modeling Spider Predation

*Collaborators:* [Michele Lynn Joyner](https://faculty.etsu.edu/joynerm/){target="_blank"}, [Edith Seier](https://faculty.etsu.edu/seier/), Chelsea Ross, J Colton Watts, Nathaniel Hancock, Michael Largent, & [Thomas C. Jones](https://www.etsu.edu/cas/biology/facultystaff/jonestc.php){target="_blank"}. ^[I was an undergraduate student for the duration of the project.]

The goal of this study was to model the predation movements of the spider species Anelosimus Studiosus using stochastic differential equations.

**Publications:**

  - [2016 Journal of theoretical biology](https://doi.org/10.1016/j.jtbi.2016.08.020){target="_blank"}
  - [2015 Mathematical biosciences and engineering](https://doi.org/10.3934/mbe.2015.12.585){target="_blank"}

**Posters:**

  - [A Stochastic Model for Cooperative Hunting of a Subsocial Arachnid](https://drive.google.com/file/d/1GF1Kj65tr9Os1F7_hhAGik1eJtJ842MA/view){target="_blank"}
  - [Expansion of a Stochastic Model for Anelosimus Studiosus Movement During Prey Capture](https://drive.google.com/file/d/1memLTW5-AGBjj10lPkH7YJkyKlYXCxsF/view){target="_blank"}
